#!/usr/bin/env bash

IPMI_HOST="192.168.0.11"
IPMI_USER="root"
IPMI_PASSWORD="calvin"

ipmi_command() {
    ipmitool -I "lanplus" -H "$IPMI_HOST" -U "$IPMI_USER" -P "$IPMI_PASSWORD" "$@"
}

ipmi_raw() {
    ipmi_command raw "$@"
}

enable_manual_fan() {
    echo "Enabling manual fan control" >&2
    ipmi_raw 0x30 0x30 0x01 0x00
}

disable_manual_fan() {
    echo "Disabling manual fan control" >&2
    ipmi_raw 0x30 0x30 0x01 0x01
}

set_fan() {
    echo "Setting fan speed to $1" >&2
    ipmi_raw 0x30 0x30 0x02 0xff "$1"
}

get_temp() {
    local temp="$(ipmi_command sdr type Temperature | sed -E 's/^.*[^0-9]([0-9]{1,2}) degrees.*$/\1/' | sort -r | head -1)"
    echo "Temp: $temp" >&2
    echo "$temp"
}

