#!/usr/bin/env bash

IPMI_HOST="192.168.13.2"
IPMI_USER="root"
IPMI_PASSWORD="calvin"

# Target temperature in C
TARGET=70

# Fan speed will be set as integer percentage SPEED*100/MAX_SPEED
# SPEED set here is the initial fan speeds
# Use MAX_SPEED big enough (e.g. 1000 or 10000). Otherwise speed increments
# might not work due to integer logic (fractional speed steps gets rounded to 0)
SPEED=2000
MAX_SPEED=10000

# These values control the increments/decrements in speed.
# Standard adjustment rate for fan speed is SPEED_INCREMENT per
# SPEED_INCREMENT_INTERVAL seconds. This rate also gets multiplied by
# the temp difference from the target temp.
SPEED_INCREMENT=50
SPEED_INCREMENT_INTERVAL=10

UPDATE_INTERVAL_SECONDS=5

# The script seems to fail if launched too early in boot. Not sure why
# If so, you can add a delay for launch by setting this variable.
# E.g. START_DELAY_SECONDS=20
START_DELAY_SECONDS=0
