#!/usr/bin/env bash

D="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "$D/ipmi-common"





declare -a SPEED
declare -a THRESHOLD

SPEED[0]="0x00"
SPEED[1]="0x0a"
SPEED[2]="0x0d"
SPEED[3]="0x11"
SPEED[4]="0x14"
SPEED[5]="0x1e"
SPEED[6]="0x28"
SPEED[7]="0x32"
SPEED[8]="0x3c"
SPEED[9]="0x50"
SPEED[10]="0x64"

TRESHOLD[0]=-1000
TRESHOLD[1]=44
TRESHOLD[2]=46
TRESHOLD[3]=48
TRESHOLD[4]=52
TRESHOLD[5]=56
TRESHOLD[6]=58
TRESHOLD[7]=60
TRESHOLD[8]=62
TRESHOLD[9]=70

N=9




cleanup() {
    echo "Exiting..." >&2
    disable_manual_fan
    exit
}

trap "cleanup" TERM INT;
trap "kill 0" EXIT




adjust() {
    local temp="$(get_temp)"
    local speed

    for i in $(seq "$N" -1 "0"); do
        if [ "$temp" -ge "${TRESHOLD[$i]}" ]; then
            break
        fi
    done

    echo "Temp over threshold $i (${TRESHOLD[$i]} C)" >&2
    speed="${SPEED[$((i+1))]}"

    set_fan "$speed"
}




# Hack since the fancontrol does not seem to workcorrectly if startedimmediately at boot
sleep 20

while true; do
    # I've had the manual fan control disable on its own once (idrac reset or
    # something?). Therefore periodically re-enable manual fan control
    enable_manual_fan
    for i in $(seq 1 20); do
        adjust
        echo "Next update in 15s..." >&2
        sleep 15
    done
done
