#!/usr/bin/env bash
D="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "$D/ipmi-config"

info() {
    echo "$@" >&2
}

warn() {
    echo "$@" >&2
}

ipmi_command() {
    ipmitool -I "lanplus" -H "$IPMI_HOST" -U "$IPMI_USER" -P "$IPMI_PASSWORD" "$@"
}

ipmi_raw() {
    ipmi_command raw "$@"
}

enable_manual_fan() {
    info "enabling manual fan control"
    ipmi_raw 0x30 0x30 0x01 0x00
}

disable_manual_fan() {
    info "disabling manual fan control"
    ipmi_raw 0x30 0x30 0x01 0x01
}

set_fan() {
    info "setting fan speed to $1"
    ipmi_raw 0x30 0x30 0x02 0xff "$1"
}

get_temps_ipmi() {
    ipmi_command sdr type Temperature \
        | ipmi_command sdr type Temperature \
        | egrep '^.*[^0-9]([0-9]{1,2}) degrees.*$' \
        | sed -E 's/^.*[^0-9]([0-9]{1,2}) degrees.*$/\1/'
}

get_temps_sysctl() {
    sysctl dev.cpu | grep 'temperature' | sed -E 's/^.* ([0-9\.]+)\.[0-9]+C$/\1/g'
}

get_temp() {
    local temp="$( (get_temps_ipmi; get_temps_sysctl) | sort -n | tail -1)"
    info "temp: $temp"
    echo "$temp"
}
